# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Samyak R Jain
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Samyak R Jain.
baseurl: "" # the subpath of the site
url: "https://samyakj.com" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg

header:
  pages:
    - name: Home
      slug: /
    - name: Projects
    - name: Blog

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: samyak24jain@gmail.com
      link: mailto:samyak24jain@gmail.com
    # - name: WeChat
    #   value: YourWeChatUsername
    #   link: "#"
  follow:
    - name: Twitter
      link: http://twitter.com/sammybuoyy
      username: "@sammybuoyy"
    - name: LinkedIn
      link: http://linkedin.com/in/samyak24jain
    - name: GitHub
      link: http://github.com/samyak24jain
    - name: RSS
      link: /feed.xml

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
